### PR TITLE
upgrade to react router v4.0.0

### PR DESCRIPTION
**Pull request by 100ideas**
`react-apollo-instagram-example` uses `react-router` v2.8.0, but the [tutorial documentation instructs](https://www.graph.cool/docs/tutorials/create-react-apps-with-apollo-client-aidae4aeg5/#installing-the-dependencies) participants to `npm install react-router --save`.

This installs the latest version of `react-router` (currently v4), which causes breaking changes.

This PR updates `react-apollo-instagram-example` to work with `react-router` v.4.0.0. Specifically, it switches `react-router` to the new `react-router-dom` submodule, which provides browserHistory implicitly.

Also upgraded `react` to the latest version (v15.4.2).

And added onClick event listener to `x` icon on DetailPage modal so clicking works as expected (I think? not sure if we need to do more to ensure the modal component is torn-down, not sure if apollo / react-router does this automatically...)

thanks for the tutorial!

### CODE REVIEW

**Comment by 100ideas** [comment]
An additional change: `create-react-app` [has dotenv baked-in](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env), so I propose using .env for setting REACT_APP_GRAPHQL_ENDPOINT. Added a commit to the PR that included a `.env.default` file to make this easy, updated the README, and added `.env` to `.gitignore`.

**Comment by stubailo** [comment]
This looks like a great improvement to me! We should also run all of the code through prettier, IMO.

**Comment by stubailo** [comment]
Also, I would suggest that adding a Yarn.lock as part of a PR like this isn't a good idea - again, my personal opinion but up to the Graphcool folks if they want Yarn in the examples.

**Comment by marktani** [comment]
That's super awesome, thanks for the PR @100ideas! here's some feedback

* > An additional change: create-react-app has dotenv baked-in, so I propose using .env for setting REACT_APP_GRAPHQL_ENDPOINT

  Could you please revert this commit? We need to find an approach for the endpoint that works together with different internal and external tooling so I'd like to tackle this at a later stage where we'll unify this behaviour across all examples.

* regarding prettier, I'm ok with having the semicolons but not super happy about it. Is there an option to turn them off? Also, could you please enable the [`singleQuote` option](https://github.com/prettier/prettier#api)?

@stubailo What's your reasoning behind this? I've had good experiences with keeping yarn.lock files in Git so far.

> Also, I would suggest that adding a Yarn.lock as part of a PR like this isn't a good idea - again, my personal opinion but up to the Graphcool folks if they want Yarn in the examples.

**Comment by 100ideas** [comment]
I share your distaste of semicolons; would have enabled it initially if @stubalio had provided an `.eslintrc` or guidelines :) 

Re yarn.lock, I included it b/c according to the [yarn docs](https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control):

> All `yarn.lock` files should be checked into source control (e.g. git or mercurial). This allows Yarn to install the same exact dependency tree across all machines, whether it be your coworker’s laptop or a CI server.
> 
> Framework and library authors should also check `yarn.lock` into source control. Don’t worry about publishing the `yarn.lock` file as it won’t have any effect on users of the library.

**Comment by marktani** [comment]
thanks for your great help @100ideas :slightly_smiling_face:

**Comment by stubailo** [comment]
Oh I wasn't saying Yarn is bad - I'm just saying it didn't match the title of the PR, which is just about adding React Router.

**Pull request merged**
